TABLES = {
    "T_JCXX": {
        "description": "检查信息表 - 患者基本信息和主病理报告",
        "fields": [
            {"name": "F_BLK", "type": "VARCHAR", "description": "病例库"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(主键)"},
            {"name": "F_SQXH", "type": "VARCHAR", "description": "申请序号"},
            {"name": "F_YZID", "type": "VARCHAR", "description": "医嘱ID"},
            {"name": "F_YZXM", "type": "VARCHAR", "description": "医嘱项目"},
            {"name": "F_XM", "type": "VARCHAR", "description": "姓名"},
            {"name": "F_XB", "type": "VARCHAR", "description": "性别"},
            {"name": "F_NL", "type": "VARCHAR", "description": "年龄"},
            {"name": "F_AGE", "type": "FLOAT", "description": "年龄数字"},
            {"name": "F_HY", "type": "VARCHAR", "description": "婚姻"},
            {"name": "F_MZ", "type": "VARCHAR", "description": "民族"},
            {"name": "F_ZY", "type": "VARCHAR", "description": "职业"},
            {"name": "F_SFZH", "type": "VARCHAR", "description": "身份证号"},
            {"name": "F_LXXX", "type": "VARCHAR", "description": "联系信息"},
            {"name": "F_BRBH", "type": "VARCHAR", "description": "病人编号"},
            {"name": "F_BRLB", "type": "VARCHAR", "description": "病人类别"},
            {"name": "F_FB", "type": "VARCHAR", "description": "费别"},
            {"name": "F_ZYH", "type": "VARCHAR", "description": "住院号"},
            {"name": "F_MZH", "type": "VARCHAR", "description": "门诊号"},
            {"name": "F_BQ", "type": "VARCHAR", "description": "病区"},
            {"name": "F_SJKS", "type": "VARCHAR", "description": "送检科室"},
            {"name": "F_CH", "type": "VARCHAR", "description": "床号"},
            {"name": "F_SJDW", "type": "VARCHAR", "description": "送检单位"},
            {"name": "F_SJYS", "type": "VARCHAR", "description": "送检医生"},
            {"name": "F_JSY", "type": "VARCHAR", "description": "接收员"},
            {"name": "F_BBLX", "type": "VARCHAR", "description": "病人类型"},
            {"name": "F_BBQK", "type": "VARCHAR", "description": "标本情况"},
            {"name": "F_JSYY", "type": "VARCHAR", "description": "拒收原因"},
            {"name": "F_SF", "type": "FLOAT", "description": "收费"},
            {"name": "F_BGYS", "type": "VARCHAR", "description": "报告医生"},
            {"name": "F_SHYS", "type": "VARCHAR", "description": "审核医生"},
            {"name": "F_BGRQ", "type": "DATE", "description": "报告日期"},
            {"name": "F_BGZT", "type": "VARCHAR", "description": "报告状态"},
            {"name": "F_BLZD", "type": "TEXT", "description": "病理诊断"},
            {"name": "F_JXSJ", "type": "TEXT", "description": "镜下所见"},
            {"name": "F_RYSJ", "type": "TEXT", "description": "肉眼所见"},
            {"name": "F_LCZD", "type": "VARCHAR", "description": "临床诊断"},
            {"name": "F_LCZL", "type": "TEXT", "description": "临床资料"},
            {"name": "F_BBMC", "type": "VARCHAR", "description": "标本名称"},
            {"name": "F_SDRQ", "type": "DATE", "description": "收到日期"},
            {"name": "F_QCYS", "type": "VARCHAR", "description": "取材医生"},
            {"name": "F_QCRQ", "type": "DATE", "description": "取材日期"},
            {"name": "F_JLY", "type": "VARCHAR", "description": "记录员"},
            {"name": "F_LKZS", "type": "INT", "description": "蜡块总数"},
            {"name": "F_CKZS", "type": "INT", "description": "材块总数"},
            {"name": "F_FY", "type": "VARCHAR", "description": "附言"},
            {"name": "F_TSJC", "type": "VARCHAR", "description": "特殊检查"},
            {"name": "F_CZYJ", "type": "TEXT", "description": "初诊意见"},
            {"name": "F_XGYJ", "type": "TEXT", "description": "修改意见"},
            {"name": "F_ZDGJC", "type": "VARCHAR", "description": "诊断关键词"},
            {"name": "F_YYX", "type": "VARCHAR", "description": "阴阳性"},
            {"name": "F_WFBGYY", "type": "VARCHAR", "description": "未发报告原因"},
            {"name": "F_BZ", "type": "VARCHAR", "description": "备注"},
            {"name": "F_BD_SFFH", "type": "VARCHAR", "description": "冰冻是否符合"},
            {"name": "F_SFCT", "type": "VARCHAR", "description": "是否采图"},
            {"name": "F_SFDY", "type": "VARCHAR", "description": "是否打印"},
            {"name": "F_BGGS", "type": "VARCHAR", "description": "报告格式"},
            {"name": "F_GDZT", "type": "VARCHAR", "description": "归档状态"},
            {"name": "F_KNHZ", "type": "INT", "description": "科内会诊状态"},
            {"name": "F_ZJYJ", "type": "VARCHAR", "description": "专家意见"},
            {"name": "F_WYYJ", "type": "TEXT", "description": "外院意见"},
            {"name": "F_SFJG", "type": "VARCHAR", "description": "随访结果"},
            {"name": "F_SFZT", "type": "INT", "description": "随访状态"},
            {"name": "F_JBBM_CN", "type": "VARCHAR", "description": "疾病编码（中文）"},
            {"name": "F_JBBM_ENG", "type": "VARCHAR", "description": "疾病编码（英文）"},
            {"name": "F_JBMC", "type": "VARCHAR", "description": "疾病名称"},
            {"name": "F_YBLH", "type": "VARCHAR", "description": "原病理号"},
            {"name": "F_SJCL", "type": "VARCHAR", "description": "送检材料"},
            {"name": "F_YBLZD", "type": "VARCHAR", "description": "原病理诊断"},
            {"name": "F_BGFSFS", "type": "VARCHAR", "description": "报告发送方式"},
            {"name": "F_SCYS", "type": "VARCHAR", "description": "收藏医生"},
            {"name": "F_SFFH", "type": "VARCHAR", "description": "是否符合"},
            {"name": "F_SPARE1", "type": "VARCHAR", "description": "复片状态"},
            {"name": "F_SPARE2", "type": "VARCHAR", "description": "复片医生"},
            {"name": "F_SPARE3", "type": "VARCHAR", "description": "评价医生"},
            {"name": "F_SPARE4", "type": "VARCHAR", "description": "复片结果"},
            {"name": "F_SPARE5", "type": "VARCHAR", "description": "审核时间"},
            {"name": "F_SPARE6", "type": "VARCHAR", "description": "复片申请时间"},
            {"name": "F_SPARE7", "type": "VARCHAR", "description": "报告到期时间"},
            {"name": "F_SPARE10", "type": "VARCHAR", "description": "结构化报告备注"},
            {"name": "F_BY1", "type": "VARCHAR", "description": "备用1"},
            {"name": "F_BY2", "type": "VARCHAR", "description": "备用2"},
            {"name": "F_TXML", "type": "VARCHAR", "description": "图像目录"},
            {"name": "F_ZPZT", "type": "VARCHAR", "description": "制片状态"},
            {"name": "F_MCYJ", "type": "VARCHAR", "description": "末次月经"},
            {"name": "F_SFJJ", "type": "VARCHAR", "description": "是否绝经"},
            {"name": "F_TBSID", "type": "INT", "description": "结构化报告ID"},
            {"name": "F_TBSMC", "type": "VARCHAR", "description": "结构化报告名称"},
            {"name": "F_QSB_DYZT", "type": "VARCHAR", "description": "签收本打印状态"},
            {"name": "F_BGWZ", "type": "VARCHAR", "description": "报告位置"},
            {"name": "F_BGWZ_QRSJ", "type": "VARCHAR", "description": "报告位置确认时间"},
            {"name": "F_BGWZ_QRCZY", "type": "VARCHAR", "description": "报告位置确认操作员"},
            {"name": "F_BBWZ", "type": "VARCHAR", "description": "标本位置"},
            {"name": "F_LKWZ", "type": "VARCHAR", "description": "蜡块位置"},
            {"name": "F_QPWZ", "type": "VARCHAR", "description": "切片位置"},
            {"name": "F_GDCZY", "type": "VARCHAR", "description": "归档操作员"},
            {"name": "F_GDSJ", "type": "VARCHAR", "description": "归档时间"},
            {"name": "F_GDBZ", "type": "VARCHAR", "description": "归档备注"},
            {"name": "F_BGLRY", "type": "VARCHAR", "description": "报告录入员"},
            {"name": "F_FZYS", "type": "VARCHAR", "description": "复诊医生"},
            {"name": "F_YL6", "type": "VARCHAR", "description": "危急值发送记录"},
            {"name": "F_YL7", "type": "VARCHAR", "description": "自助打印记录"},
            {"name": "F_YL8", "type": "VARCHAR", "description": "申请复片的医生"},
            {"name": "F_YL9", "type": "VARCHAR", "description": "蜡块块数"},
            {"name": "F_YL10", "type": "VARCHAR", "description": "初步诊断"},
            {"name": "F_ICD10_BM1", "type": "VARCHAR", "description": "ICD10编码1"},
            {"name": "F_ICD10_MC1", "type": "VARCHAR", "description": "ICD10名称1"},
            {"name": "F_ICD10_BM2", "type": "VARCHAR", "description": "ICD10编码2"},
            {"name": "F_ICD10_MC2", "type": "VARCHAR", "description": "ICD10名称2"},
            {"name": "F_BL1", "type": "VARCHAR", "description": "特检医嘱申请医生"},
            {"name": "F_BL2", "type": "VARCHAR", "description": "科内会诊申请医生"},
            {"name": "F_BL3", "type": "VARCHAR", "description": "随访申请医生"},
            {"name": "F_FBSJ", "type": "DATETIME", "description": "发布时间"},
            {"name": "F_FBYS", "type": "VARCHAR", "description": "发布医生"},
            {"name": "F_PDFSCSJ", "type": "VARCHAR", "description": "PDF生成时间"},
            {"name": "F_JPGSCSJ", "type": "VARCHAR", "description": "JPG生成时间"},
            {"name": "F_PDFCLSJ", "type": "VARCHAR", "description": "PDF处理时间"},
        ]
    },
    "T_BCBG": {
        "description": "补充报告表 - 补充报告信息(主要用于免疫组化报告)",
        "fields": [
            {"name": "F_ID", "type": "INT", "description": "主键ID"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键)"},
            {"name": "F_BC_BGXH", "type": "INT", "description": "补充报告序号"},
            {"name": "F_BC_BGYS", "type": "VARCHAR", "description": "报告医生"},
            {"name": "F_BC_SHYS", "type": "VARCHAR", "description": "审核医生"},
            {"name": "F_BC_BGRQ", "type": "VARCHAR", "description": "报告日期"},
            {"name": "F_BCZD", "type": "TEXT", "description": "补充诊断"},
            {"name": "F_BC_BGZT", "type": "VARCHAR", "description": "报告状态"},
            {"name": "F_BC_FZYS", "type": "VARCHAR", "description": "复诊医生"},
            {"name": "F_BC_DYZT", "type": "VARCHAR", "description": "打印状态"},
            {"name": "F_BC_QSB_DYZT", "type": "VARCHAR", "description": "签收本打印状态"},
            {"name": "F_BC_BGWZ", "type": "VARCHAR", "description": "报告位置"},
            {"name": "F_BC_BGWZ_QRSJ", "type": "VARCHAR", "description": "报告位置确认时间"},
            {"name": "F_BC_BGWZ_QRCZY", "type": "VARCHAR", "description": "报告位置确认操作员"},
            {"name": "F_BC_BZ", "type": "VARCHAR", "description": "备注"},
            {"name": "F_BC_SPARE5", "type": "VARCHAR", "description": "审核时间"},
            {"name": "F_BC_JXSJ", "type": "VARCHAR", "description": "镜下所见"},
            {"name": "F_BC_TSJC", "type": "VARCHAR", "description": "特殊检查"},
            {"name": "F_BC_BGGS", "type": "VARCHAR", "description": "报告格式"},
            {"name": "F_BC_FBSJ", "type": "DATETIME", "description": "发布时间"},
            {"name": "F_BC_FBYS", "type": "VARCHAR", "description": "发布医生"},
            {"name": "F_pdfscsj", "type": "VARCHAR", "description": "PDF生成时间"},
            {"name": "F_BC_SPARE1", "type": "VARCHAR", "description": "复片状态"},
            {"name": "F_BC_SPARE2", "type": "VARCHAR", "description": "复片医生"},
            {"name": "F_BC_SPARE6", "type": "VARCHAR", "description": "申请时间"},
            {"name": "F_JPGSCSJ", "type": "VARCHAR", "description": "JPG生成时间"},
            {"name": "F_BC_PDFCLSJ", "type": "VARCHAR", "description": "PDF处理时间"},
            {"name": "F_BCDYCS", "type": "INT", "description": "补充打印次数"},
        ]
    },
    "T_BDBG": {
        "description": "冰冻报告表 - 冰冻病理报告信息",
        "fields": [
            {"name": "F_ID", "type": "INT", "description": "主键ID"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键)"},
            {"name": "F_BD_BGXH", "type": "INT", "description": "冰冻报告序号"},
            {"name": "F_BD_BGYS", "type": "VARCHAR", "description": "报告医生"},
            {"name": "F_BD_SHYS", "type": "VARCHAR", "description": "审核医生"},
            {"name": "F_BD_BGRQ", "type": "VARCHAR", "description": "报告日期"},
            {"name": "F_BDZD", "type": "TEXT", "description": "冰冻诊断"},
            {"name": "F_BC_BGZT", "type": "VARCHAR", "description": "报告状态"},
            {"name": "F_BD_ZPR", "type": "VARCHAR", "description": "制片人"},
            {"name": "F_BD_SDRQ", "type": "VARCHAR", "description": "收到日期"},
            {"name": "F_BD_QCYS", "type": "VARCHAR", "description": "取材医生"},
            {"name": "F_BD_CFYY", "type": "VARCHAR", "description": "迟发原因"},
            {"name": "F_BD_ZPS", "type": "VARCHAR", "description": "制片数"},
            {"name": "F_BD_BZ", "type": "VARCHAR", "description": "备注"},
            {"name": "F_BD_FZYS", "type": "VARCHAR", "description": "复诊医生"},
            {"name": "F_BD_DYZT", "type": "VARCHAR", "description": "打印状态"},
            {"name": "F_BD_QSB_DYZT", "type": "VARCHAR", "description": "签收本打印状态"},
            {"name": "F_BD_BGWZ", "type": "VARCHAR", "description": "报告位置"},
            {"name": "F_BD_BGWZ_QRSJ", "type": "VARCHAR", "description": "报告位置确认时间"},
            {"name": "F_BD_BGWZ_QRCZY", "type": "VARCHAR", "description": "报告位置确认操作员"},
            {"name": "F_ZPSJ", "type": "VARCHAR", "description": "制片时间"},
            {"name": "F_LTSJ", "type": "VARCHAR", "description": "离体时间"},
            {"name": "F_ZPKSSJ", "type": "VARCHAR", "description": "制片开始时间"},
            {"name": "F_BD_FBSJ", "type": "DATETIME", "description": "发布时间"},
            {"name": "F_BD_FBYS", "type": "VARCHAR", "description": "发布医生"},
            {"name": "F_BD_BBMC", "type": "VARCHAR", "description": "标本名称"},
            {"name": "F_BD_RYSJ", "type": "VARCHAR", "description": "肉眼所见"},
            {"name": "F_BD_SPARE5", "type": "VARCHAR", "description": "审核时间"},
            {"name": "F_pdfscsj", "type": "VARCHAR", "description": "PDF生成时间"},
            {"name": "F_JPGSCSJ", "type": "VARCHAR", "description": "JPG生成时间"},
            {"name": "F_BD_PDFCLSJ", "type": "VARCHAR", "description": "PDF处理时间"},
            {"name": "F_BDDYCS", "type": "INT", "description": "冰冻打印次数"},
        ]
    },
    "T_LK": {
        "description": "蜡块表 - 蜡块信息",
        "fields": [
            {"name": "F_ID", "type": "INT", "description": "主键ID"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键)"},
            {"name": "F_RWLY", "type": "VARCHAR", "description": "任务来源"},
            {"name": "F_QCXH", "type": "VARCHAR", "description": "取材序号"},
            {"name": "F_LKH", "type": "VARCHAR", "description": "蜡块号"},
            {"name": "F_LKZT", "type": "VARCHAR", "description": "蜡块状态"},
            {"name": "F_QPZT", "type": "VARCHAR", "description": "切片状态"},
            {"name": "F_CZY", "type": "VARCHAR", "description": "操作员"},
            {"name": "F_BMSJ", "type": "DATETIME", "description": "包埋时间"},
            {"name": "F_GDZT", "type": "VARCHAR", "description": "归档状态"},
            {"name": "F_GDCZY", "type": "VARCHAR", "description": "归档操作员"},
            {"name": "F_GDSJ", "type": "VARCHAR", "description": "归档时间"},
            {"name": "F_BZ", "type": "VARCHAR", "description": "备注"},
        ]
    },
    "T_QP": {
        "description": "切片表 - 切片信息",
        "fields": [
            {"name": "F_ID", "type": "INT", "description": "主键ID"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键)"},
            {"name": "F_RWLY", "type": "VARCHAR", "description": "任务来源"},
            {"name": "F_LKH", "type": "VARCHAR", "description": "蜡块号(外键关联T_LK)"},
            {"name": "F_YZH", "type": "VARCHAR", "description": "医嘱号"},
            {"name": "F_QPTMH", "type": "VARCHAR", "description": "切片条码号"},
            {"name": "F_QPXH", "type": "INT", "description": "切片序号"},
            {"name": "F_QPBH", "type": "VARCHAR", "description": "切片编码"},
            {"name": "F_QPSM", "type": "VARCHAR", "description": "切片说明"},
            {"name": "F_CZY", "type": "VARCHAR", "description": "操作员"},
            {"name": "F_QPSJ", "type": "DATETIME", "description": "切片时间"},
            {"name": "F_DYZT", "type": "VARCHAR", "description": "打印状态"},
            {"name": "F_JGPJ", "type": "VARCHAR", "description": "结果评价"},
            {"name": "F_PJR", "type": "VARCHAR", "description": "评价人"},
            {"name": "F_QPZT", "type": "VARCHAR", "description": "切片状态"},
            {"name": "F_QPTMH2", "type": "VARCHAR", "description": "切片条码号2"},
            {"name": "F_GDZT", "type": "VARCHAR", "description": "归档状态"},
            {"name": "F_GDCZY", "type": "VARCHAR", "description": "归档操作员"},
            {"name": "F_GDSJ", "type": "VARCHAR", "description": "归档时间"},
            {"name": "F_BZ", "type": "VARCHAR", "description": "备注"},
            {"name": "F_TJH", "type": "VARCHAR", "description": "特检号"},
            {"name": "F_ZXSB", "type": "VARCHAR", "description": "执行设备"},
            {"name": "F_RSY", "type": "VARCHAR", "description": "染色员"},
            {"name": "F_RSSJ", "type": "DATETIME", "description": "染色时间"},
            {"name": "F_YZSQYS", "type": "VARCHAR", "description": "医嘱申请时间"},
            {"name": "F_PJSJ", "type": "VARCHAR", "description": "评价时间"},
            {"name": "F_CLJG", "type": "VARCHAR", "description": "处理结果"},
            {"name": "F_CLR", "type": "VARCHAR", "description": "处理人"},
            {"name": "F_CLRQ", "type": "VARCHAR", "description": "处理日期"},
            {"name": "F_QPJJDDYZT", "type": "VARCHAR", "description": "切片交接单打印状态"},
            {"name": "F_QPJJDDYCZY", "type": "VARCHAR", "description": "切片交接单打印操作员"},
            {"name": "F_QPJJDDYSJ", "type": "VARCHAR", "description": "切片交接单打印时间"},
            {"name": "F_QPJJZT", "type": "VARCHAR", "description": "切片交接状态"},
            {"name": "F_QPJJCZY", "type": "VARCHAR", "description": "切片交接操作员"},
            {"name": "F_QPJJSJ", "type": "VARCHAR", "description": "切片交接时间"},
        ]
    },
    "T_JHP": {
        "description": "借还片表 - 蜡块/切片借阅归还记录",
        "fields": [
            {"name": "F_ID", "type": "INT", "description": "主键ID"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键)"},
            {"name": "F_XM", "type": "VARCHAR", "description": "姓名"},
            {"name": "F_BM", "type": "VARCHAR", "description": "病名"},
            {"name": "F_JHPBH", "type": "VARCHAR", "description": "借还片编号"},
            {"name": "F_JHP_QPSM", "type": "VARCHAR", "description": "切片说明"},
            {"name": "F_JHP_QPTMH", "type": "VARCHAR", "description": "切片条码号"},
            {"name": "F_JHP_LKSM", "type": "VARCHAR", "description": "蜡块说明"},
            {"name": "F_JHP_LKH", "type": "VARCHAR", "description": "蜡块号"},
            {"name": "F_YJ", "type": "INT", "description": "押金"},
            {"name": "F_JHPZT", "type": "VARCHAR", "description": "借还片状态"},
            {"name": "F_JCCZY", "type": "VARCHAR", "description": "借出操作员"},
            {"name": "F_JCSJ", "type": "DATETIME", "description": "借出时间"},
            {"name": "F_GHCZY", "type": "VARCHAR", "description": "归还操作员"},
            {"name": "F_GHSJ", "type": "DATETIME", "description": "归还时间"},
            {"name": "F_JHPLX", "type": "VARCHAR", "description": "借还片类型"},
            {"name": "F_JHPYY", "type": "VARCHAR", "description": "借还片原因"},
            {"name": "F_SFZH", "type": "VARCHAR", "description": "身份证号"},
            {"name": "F_HZGX", "type": "VARCHAR", "description": "患者关系"},
            {"name": "F_JYR", "type": "VARCHAR", "description": "借阅人"},
            {"name": "F_LXXX", "type": "VARCHAR", "description": "联系信息"},
            {"name": "F_BZ", "type": "VARCHAR", "description": "备注"},
            {"name": "F_QPZS", "type": "VARCHAR", "description": "切片张数"},
        ]
    },
    "T_TX": {
        "description": "图像表 - 患者病理图像记录",
        "fields": [
            {"name": "F_ID", "type": "INT", "description": "主键ID"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键)"},
            {"name": "F_TXM", "type": "VARCHAR", "description": "图像名"},
            {"name": "F_TXSM", "type": "VARCHAR", "description": "图像说明"},
            {"name": "F_SFDY", "type": "INT", "description": "是否打印"},
            {"name": "F_TXLB", "type": "VARCHAR", "description": "图像类别"},
            {"name": "F_CZY", "type": "VARCHAR", "description": "操作员"},
            {"name": "F_CZYSJ", "type": "VARCHAR", "description": "操作时间"},
            {"name": "F_PXID", "type": "INT", "description": "排序ID"},
            {"name": "F_BZXX", "type": "VARCHAR", "description": "备注信息"},
        ]
    },
    "T_BGHJ": {
        "description": "报告痕迹表 - 从登记到报告发放的所有动作记录",
        "fields": [
            {"name": "F_ID", "type": "INT", "description": "主键ID"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键)"},
            {"name": "F_RQ", "type": "DATE", "description": "日期"},
            {"name": "F_CZY", "type": "VARCHAR", "description": "操作员"},
            {"name": "F_WZ", "type": "VARCHAR", "description": "位置（计算机名）"},
            {"name": "F_DZ", "type": "VARCHAR", "description": "动作"},
            {"name": "F_NR", "type": "TEXT", "description": "内容"},
            {"name": "F_EXEMC", "type": "VARCHAR", "description": "工作站类型(QP/BM/BPS/RPT)"},
            {"name": "F_CTMC", "type": "VARCHAR", "description": "窗体名称"},
        ]
    },
    "T_JSYZ": {
        "description": "技术医嘱表 - 患者技术医嘱信息",
        "fields": [
            {"name": "F_ID", "type": "INT", "description": "主键ID"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键)"},
            {"name": "F_JSYZH", "type": "VARCHAR", "description": "技术医嘱号"},
            {"name": "F_YZLX", "type": "VARCHAR", "description": "医嘱类型"},
            {"name": "F_LKH", "type": "VARCHAR", "description": "蜡块号(外键)"},
            {"name": "F_SL", "type": "INT", "description": "数量"},
            {"name": "F_SQYS", "type": "VARCHAR", "description": "申请医生"},
            {"name": "F_SQSJ", "type": "DATETIME", "description": "申请时间"},
            {"name": "F_YZZT", "type": "VARCHAR", "description": "医嘱状态"},
            {"name": "F_ZXSJ", "type": "VARCHAR", "description": "执行时间"},
            {"name": "F_ZXR", "type": "VARCHAR", "description": "执行人"},
            {"name": "F_BZ", "type": "VARCHAR", "description": "备注"},
            {"name": "F_YZLRY", "type": "VARCHAR", "description": "医嘱录入员"},
            {"name": "F_KDD", "type": "VARCHAR", "description": "开单地"},
            {"name": "F_JSYZYY", "type": "VARCHAR", "description": "技术医嘱原因"},
        ]
    },
    "T_TJYZ": {
        "description": "特检医嘱表 - 患者特检医嘱(免疫组化等)",
        "fields": [
            {"name": "F_ID", "type": "INT", "description": "主键ID"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键)"},
            {"name": "F_TJYZH", "type": "VARCHAR", "description": "特检医嘱号"},
            {"name": "F_YZLX", "type": "VARCHAR", "description": "医嘱类型"},
            {"name": "F_LKH", "type": "VARCHAR", "description": "蜡块号(外键)"},
            {"name": "F_BJW", "type": "VARCHAR", "description": "标记物"},
            {"name": "F_SL", "type": "INT", "description": "数量"},
            {"name": "F_BX", "type": "VARCHAR", "description": "表型"},
            {"name": "F_QD", "type": "VARCHAR", "description": "强度"},
            {"name": "F_BZ", "type": "VARCHAR", "description": "备注"},
            {"name": "F_SQYS", "type": "VARCHAR", "description": "申请医生"},
            {"name": "F_SQSJ", "type": "VARCHAR", "description": "申请时间"},
            {"name": "F_YZZT", "type": "VARCHAR", "description": "医嘱状态"},
            {"name": "F_ZXSJ", "type": "DATETIME", "description": "执行时间"},
            {"name": "F_ZXR", "type": "VARCHAR", "description": "执行人"},
            {"name": "F_DKRH", "type": "VARCHAR", "description": "特检号"},
            {"name": "F_LX", "type": "VARCHAR", "description": "类型"},
            {"name": "F_CJ", "type": "VARCHAR", "description": "结果医生"},
            {"name": "F_FF", "type": "VARCHAR", "description": "方法"},
            {"name": "F_ZXSB", "type": "VARCHAR", "description": "执行设备"},
            {"name": "F_FSSJ", "type": "VARCHAR", "description": "发送时间"},
            {"name": "F_YZLRY", "type": "VARCHAR", "description": "医嘱录入员"},
            {"name": "F_ZXXH", "type": "INT", "description": "执行序号"},
            {"name": "F_KDD", "type": "VARCHAR", "description": "开单地"},
            {"name": "F_SFZTCZY", "type": "VARCHAR", "description": "收费状态操作员"},
            {"name": "F_SFZTCZSJ", "type": "VARCHAR", "description": "收费状态操作时间"},
            {"name": "F_TJHSCSJ", "type": "VARCHAR", "description": "特检号生成时间"},
            {"name": "F_RSGZBDYZT", "type": "VARCHAR", "description": "染色表打印状态"},
            {"name": "F_TJH", "type": "VARCHAR", "description": "特检号"},
            {"name": "F_ZLBL", "type": "VARCHAR", "description": "肿瘤比例"},
            {"name": "F_YDWLKH", "type": "VARCHAR", "description": "原单位蜡块号"},
            {"name": "F_TJHSCCZY", "type": "VARCHAR", "description": "特检号生成操作员"},
            {"name": "F_TJYZ_JCMD", "type": "VARCHAR", "description": "特检医嘱检测目的"},
        ]
    },
    "T_QCMX": {
        "description": "取材明细表 - 取材明细信息",
        "fields": [
            {"name": "F_ID", "type": "INT", "description": "主键ID"},
            {"name": "F_PXID", "type": "INT", "description": "排序号"},
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键)"},
            {"name": "F_RWLY", "type": "VARCHAR", "description": "任务来源"},
            {"name": "F_QCXH", "type": "INT", "description": "取材序号"},
            {"name": "F_ZZMC", "type": "VARCHAR", "description": "组织名称"},
            {"name": "F_CKS", "type": "INT", "description": "材块数"},
            {"name": "F_QCYS", "type": "VARCHAR", "description": "取材医生"},
            {"name": "F_QCRQ", "type": "VARCHAR", "description": "取材日期"},
            {"name": "F_BMZT", "type": "VARCHAR", "description": "包埋状态"},
            {"name": "F_SM", "type": "VARCHAR", "description": "说明"},
            {"name": "F_BZ", "type": "VARCHAR", "description": "备注"},
            {"name": "F_SJZT", "type": "VARCHAR", "description": "上机状态"},
            {"name": "F_QCSJ", "type": "VARCHAR", "description": "取材时间"},
            {"name": "F_JLY", "type": "VARCHAR", "description": "记录员"},
            {"name": "F_HDZT", "type": "VARCHAR", "description": "核对状态"},
            {"name": "F_HDR", "type": "VARCHAR", "description": "核对人"},
            {"name": "F_HDSJ", "type": "VARCHAR", "description": "核对时间"},
            {"name": "F_LGLINK_CLJG", "type": "VARCHAR", "description": "处理结果"},
            {"name": "F_LGLINK_CLR", "type": "VARCHAR", "description": "处理人"},
            {"name": "F_LGLINK_CLSJ", "type": "DATETIME", "description": "处理时间"},
            {"name": "F_LGLINK_PJR", "type": "VARCHAR", "description": "评价人"},
            {"name": "F_LGLINK_PJSJ", "type": "DATETIME", "description": "评价时间"},
            {"name": "F_QCMX_DHHZ", "type": "VARCHAR", "description": "打号后缀"},
            {"name": "F_BD_BGXH", "type": "INT", "description": "冰冻报告序号"},
        ]
    },
    "T_TBS_BG": {
        "description": "TBS报告表 - 结构化报告字段内容",
        "fields": [
            {"name": "F_BLH", "type": "VARCHAR", "description": "病理号(外键/主键)"},
            {"name": "F_TBS_JYFF", "type": "VARCHAR", "description": "检验方法"},
            {"name": "F_TBS_MPFX", "type": "VARCHAR", "description": "涂片分析"},
            {"name": "F_TBS_XBXM1", "type": "VARCHAR", "description": "细胞项目1"},
            {"name": "F_TBS_XBXM2", "type": "VARCHAR", "description": "细胞项目2"},
            {"name": "F_TBS_XBXM3", "type": "VARCHAR", "description": "细胞项目3"},
            {"name": "F_TBS_XBXM4", "type": "VARCHAR", "description": "细胞项目4"},
            {"name": "F_TBS_XBXM5", "type": "VARCHAR", "description": "细胞项目5"},
            {"name": "F_TBS_XBXM6", "type": "VARCHAR", "description": "细胞项目6"},
            {"name": "F_TBSZD", "type": "TEXT", "description": "TBS诊断"},
            {"name": "F_TBS_BBMYD", "type": "VARCHAR", "description": "标本满意度"},
            {"name": "F_TBS_YZCD", "type": "VARCHAR", "description": "炎症程度"},
            {"name": "F_TBS_ZGBL", "type": "VARCHAR", "description": "鳞柱比"},
            {"name": "F_TBS_BCYJ1", "type": "VARCHAR", "description": "补充意见1"},
            {"name": "F_TBS_BCYJ2", "type": "VARCHAR", "description": "补充意见2"},
            {"name": "F_TBS_XJRQ", "type": "VARCHAR", "description": "新建日期"},
            {"name": "F_TBS_ZPR", "type": "VARCHAR", "description": "制片人"},
            {"name": "F_TBS_XBL", "type": "VARCHAR", "description": "细胞量"},
        ]
    },
    "T_DK_CS": {
        "description": "常用查询配置表 - 工作站快速列表配置SQL",
        "fields": [
            {"name": "F_EXEMC", "type": "VARCHAR", "description": "工作站类别"},
            {"name": "F_MC", "type": "VARCHAR", "description": "列表名称"},
            {"name": "F_SQL", "type": "TEXT", "description": "快速列表SQL"},
        ],
    },
    "T_LB_CS": {
        "description": "列表字段配置表 - 工作站展示字段与查询筛选配置",
        "fields": [
            {"name": "F_EXEMC", "type": "VARCHAR", "description": "工作站类别"},
            {"name": "F_LX", "type": "VARCHAR", "description": "配置类型"},
            {"name": "F_DKCX_PXH", "type": "INT", "description": "筛选显示排序"},
        ],
    },
    "T_BBLC_CYC": {
        "description": "报告流程常用词表 - 标本名称/临床诊断常用词",
        "fields": [],
    },
    "T_BJW_CYC": {
        "description": "标记物常用词表 - 特检标记物说明配置",
        "fields": [],
    },
    "T_BLK_CS": {
        "description": "病例库参数表 - 病例库基础配置",
        "fields": [],
    },
    "T_CGBW_TREE": {
        "description": "常用词部位目录表 - 诊断常用词一二级部位结构",
        "fields": [],
    },
    "T_CG_CYC": {
        "description": "诊断常用词表 - 与部位目录关联的常用词内容",
        "fields": [],
    },
    "T_CYC": {
        "description": "结构化字段映射表 - 模板字段名称配置",
        "fields": [],
    },
    "T_CYC_FL": {
        "description": "常用词分类表 - 常用词分类维护",
        "fields": [],
    },
    "T_TBS_SY": {
        "description": "结构化报告模板表 - TBS模板与分类配置",
        "fields": [],
    },
    "T_PDFJPG_SCCW": {
        "description": "PDF/JPG生成错误表 - 报告文件生成失败记录",
        "fields": [],
    },
    "T_YH": {
        "description": "用户表 - 系统用户信息",
        "fields": [],
    },
}
